Playbook introduction extractor
PopulateTools/ansible-doc-generator pull request #17
Opened 2021-01-07 15:23 UTC by eltercero

Extract a title and comment from the Playbook to serve as an introduction to the guide.

2021-01-08 06:43 UTC, ferblape commented on spec/support/files/example_playbook.yml
> +---
Just being picky here, could you update the comments to be in English? Because we are opening this repo so I prefer everything in English. Thanks!

2021-01-08 06:43 UTC, ferblape commented on lib/ansible_doc_generator/doc_generator/extractor_helper.rb
> +# frozen_string_literal: true
You extracted the extractor!

2021-01-08 07:01 UTC, eltercero commented on lib/ansible_doc_generator/doc_generator/extractor_helper.rb
> +# frozen_string_literal: true
we have to go deeper!

2021-01-11 04:59 UTC, ferblape requested changes
All good except there's no reference in the README 📜

2021-01-11 07:21 UTC, ferblape approved these changes

2021-01-11 07:21 UTC, merged